name: Build

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: mise install
        uses: jdx/mise-action@v2
        with:
          version: 2025.7.18
          install: true
          cache: true
          experimental: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: mise install
        uses: jdx/mise-action@v2
        with:
          version: 2025.7.18
          install: true
          cache: true
          experimental: true
          working_directory: ui
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser (release)
        uses: goreleaser/goreleaser-action@v6
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          args: "release --clean"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser (snapshot)
        uses: goreleaser/goreleaser-action@v6
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          args: "build --snapshot --clean --single-target"
